queue_rules:
  - name: default
    conditions:
      - 'status-success~=Build & Test - Nixpkgs \(ubuntu-.*\).*'
      - 'status-success~=Build & Test - Nixpkgs \(macos-.*\).*'
      - 'status-success~=Build & Test - bindist \(ubuntu-.*\).*'
      - 'status-success~=Build & Test - bindist \(macos-.*\).*'
      - 'status-success~=Build & Test - bindist \(windows-.*\).*'
      - 'status-success~=Build & Test - Cross.*'
      - "status-success=deploy/netlify"

pull_request_rules:
  - name: automatic merge
    conditions:
      - 'status-success~=Build & Test - Nixpkgs \(ubuntu-.*\).*'
      - 'status-success~=Build & Test - Nixpkgs \(macos-.*\).*'
      - 'status-success~=Build & Test - bindist \(ubuntu-.*\).*'
      - 'status-success~=Build & Test - bindist \(macos-.*\).*'
      - 'status-success~=Build & Test - bindist \(windows-.*\).*'
      - 'status-success~=Build & Test - Cross.*'
      - "status-success=deploy/netlify"
      - "#approved-reviews-by>=1"
      - "label=merge-queue"
      - "base=master"
    actions:
      queue:
        name: default
        method: merge

  - name: delete head branch after merge
    conditions:
      - merged
      - closed
    actions:
      delete_head_branch: {}

  - name: remove from merge-queue after merge
    conditions:
      - merged
    actions:
      label:
        remove:
          - "merge-queue"
